version: 0.1
phases:
  install:
    commands:      
      - npm install -g npm
      - npm install -g serverless@1.41.1
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - mkdir -p target/dev
      - mkdir target/prod
      - serverless package --package target/dev --stage dev -v -r us-east-1
      - serverless package --package target/prod --stage prod -v -r us-east-1

artifacts:
  files:
  - target/**/*
  - serverless.yml
  - serverless.env.yml
  - serverless.functions.yml
  - serverless.resources.yml
  - deploy.sh
  - serverless-state.json