Resources:
  ServerlessApiGateway:
    Type: AWS::ApiGateway::RestApi
    DeletionPolicy: Delete
    Properties:
      Name: serverlessApiGateway

  # RequestValidatorAll:
  #   Type: AWS::ApiGateway::RequestValidator
  #   Properties:
  #     Name: all
  #     RestApiId: !Ref ServerlessApiGateway
  #     ValidateRequestBody: true
  #     ValidateRequestParameters: true

Outputs:
  apiGatewayRestApiId:
    Value:
      Ref: ServerlessApiGateway
    Export:
      Name: ApiGateway-restApiId
  apiGatewayRestApiRootResourceId:
    Value:
      Fn::GetAtt:
        - ServerlessApiGateway
        - RootResourceId
    Export:
      Name: ApiGateway-rootResourceId
